# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jpuckett/Downloads/circleNoHooke

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jpuckett/Downloads/circleNoHooke

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jpuckett/Downloads/circleNoHooke/CMakeFiles /Users/jpuckett/Downloads/circleNoHooke/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jpuckett/Downloads/circleNoHooke/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named circlePack

# Build rule for target.
circlePack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 circlePack
.PHONY : circlePack

# fast build rule for target.
circlePack/fast:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/build
.PHONY : circlePack/fast

src/atom.o: src/atom.cpp.o

.PHONY : src/atom.o

# target to build an object file
src/atom.cpp.o:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/atom.cpp.o
.PHONY : src/atom.cpp.o

src/atom.i: src/atom.cpp.i

.PHONY : src/atom.i

# target to preprocess a source file
src/atom.cpp.i:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/atom.cpp.i
.PHONY : src/atom.cpp.i

src/atom.s: src/atom.cpp.s

.PHONY : src/atom.s

# target to generate assembly for a file
src/atom.cpp.s:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/atom.cpp.s
.PHONY : src/atom.cpp.s

src/dem.o: src/dem.cpp.o

.PHONY : src/dem.o

# target to build an object file
src/dem.cpp.o:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/dem.cpp.o
.PHONY : src/dem.cpp.o

src/dem.i: src/dem.cpp.i

.PHONY : src/dem.i

# target to preprocess a source file
src/dem.cpp.i:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/dem.cpp.i
.PHONY : src/dem.cpp.i

src/dem.s: src/dem.cpp.s

.PHONY : src/dem.s

# target to generate assembly for a file
src/dem.cpp.s:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/dem.cpp.s
.PHONY : src/dem.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/params.o: src/params.cpp.o

.PHONY : src/params.o

# target to build an object file
src/params.cpp.o:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/params.cpp.o
.PHONY : src/params.cpp.o

src/params.i: src/params.cpp.i

.PHONY : src/params.i

# target to preprocess a source file
src/params.cpp.i:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/params.cpp.i
.PHONY : src/params.cpp.i

src/params.s: src/params.cpp.s

.PHONY : src/params.s

# target to generate assembly for a file
src/params.cpp.s:
	$(MAKE) -f CMakeFiles/circlePack.dir/build.make CMakeFiles/circlePack.dir/src/params.cpp.s
.PHONY : src/params.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... circlePack"
	@echo "... src/atom.o"
	@echo "... src/atom.i"
	@echo "... src/atom.s"
	@echo "... src/dem.o"
	@echo "... src/dem.i"
	@echo "... src/dem.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/params.o"
	@echo "... src/params.i"
	@echo "... src/params.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

